name: Build and deploy to GitHub Pages

permissions:
  id-token: write
  contents: read
  pages: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If you have a build step (npm, hugo, etc) add it here.
      # Example (uncomment if needed):
      # - name: Install dependencies
      #   run: npm ci
      # - name: Build
      #   run: npm run build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          # Set this to the folder with your static site output.
          # Use './' if the static files are in the repo root.
          path: './'

  deploy:
  needs: build
  runs-on: ubuntu-latest
  environment:
    name: github-pages
  steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
